apiVersion: v1

kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: myapp

spec:
  containers:
    - name: nginx-containers
      image: bash
      env:
      - name: username
        valueFrom:
          secretKeyRef:
           name: mysecret
           key: username
      - name: pwd
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
      command: ["echo"]
      args: ["${username} ${pwd}"] 