apiVersion: apps/v1

kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: myapp
    type: frontend

spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-containers
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: myapp  